### ISSUE TITLE
a127 usergrid start fails

### ISSUE THREAD

**Issue by RainerAtSpirit** [apigee-127/usergrid-npm#2]
This seems to be a two fold issue. One side is simply related to a corrupted download #1. 
But I downloaded the file from the Snapshot mentioned in the related thread, made sure that the file size is correct (48581037) and I'm still unable to start usergrid on Windows 8.1

``` bash
$ a127 usergrid start
starting...
timeout
failed to start. Log tail:
INFO: Registering Spring bean, rootResource, of type org.apache.usergrid.rest.Ro
otResource as a root resource class
Feb 01, 2015 4:45:29 PM com.sun.jersey.spi.spring.container.SpringComponentProvi
derFactory registerSpringBeans
INFO: Registering Spring bean, systemResource, of type org.apache.usergrid.rest.
SystemResource as a root resource class
Feb 01, 2015 4:45:29 PM com.sun.jersey.spi.spring.container.SpringComponentProvi
derFactory registerSpringBeans
INFO: Registering Spring bean, propertiesResource, of type org.apache.usergrid.r
est.test.PropertiesResource as a root resource class
Feb 01, 2015 4:45:30 PM com.sun.jersey.server.impl.application.WebApplicationImp
l _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.18 11/22/2013 01:21 AM'
Feb 01, 2015 4:45:30 PM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer] Started.
```

**Comment by theganyo** [comment]
Others have reported being able to run on Windows 8.1, so that doesn't seem to be the issue. I've passed your issue around and the general consensus is that it is possibly a port conflict with Cassandra. Please be sure that you aren't already running Cassandra when you start usergrid. If you're not, you may need to track down if another application is using a [Cassandra port](http://stackoverflow.com/questions/2359159/cassandra-port-usage-how-are-the-ports-used).

The other thing that may help us debug this issue is to run the command in debug mode like so:

`DEBUG=* a127 usergrid start`

**Comment by RainerAtSpirit** [comment]
I don't see any of the mentioned ports used before starting and turning off the Windows firewall doesn't make a difference.
I've attached the output when starting with the DEBUG option, but I couldn't spot anything obvious that explains the timeout.

Interestingly enough the http server started on port 8080, but throws the following error.

![image](https://cloud.githubusercontent.com/assets/581644/6016851/00342d20-ab88-11e4-91e4-f5056fc3f11a.png)

``` bash
$ DEBUG=* a127 usergrid start
starting...
spawnArgs: -jar,C:\Users\Rainer\.a127\usergrid\usergrid-launcher-0.0.29.jar,-nog
ui,-db,-port,8080
spawnOpts: {"cwd":"C:\\Users\\Rainer\\.a127\\usergrid","detached":true,"stdio":[
"ignore",3,4]}
timeout
failed to start. Log tail:
INFO: Registering Spring bean, rootResource, of type org.apache.usergrid.rest.Ro
otResource as a root resource class
Feb 03, 2015 9:19:47 AM com.sun.jersey.spi.spring.container.SpringComponentProvi
derFactory registerSpringBeans
INFO: Registering Spring bean, systemResource, of type org.apache.usergrid.rest.
SystemResource as a root resource class
Feb 03, 2015 9:19:47 AM com.sun.jersey.spi.spring.container.SpringComponentProvi
derFactory registerSpringBeans
INFO: Registering Spring bean, propertiesResource, of type org.apache.usergrid.r
est.test.PropertiesResource as a root resource class
Feb 03, 2015 9:19:47 AM com.sun.jersey.server.impl.application.WebApplicationImp
l _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.18 11/22/2013 01:21 AM'
Feb 03, 2015 9:19:48 AM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer] Started.
```

**Comment by RainerAtSpirit** [comment]
Now I'm puzzled. Brought up a new ubuntu 14.04 instance and after installing the prerequisites node

``` bash
rainer@ubuntu:~$ node -v
v0.10.36
```

and java 

``` bash
rainer@ubuntu:~$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

 I got the following.

``` bash
rainer@ubuntu:~$ a127 usergrid start
starting...
.......timeout
failed to start. Log tail:
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Feb 03, 2015 1:43:46 PM org.glassfish.grizzly.http.server.NetworkListener start
INFO: Started listener bound to [0.0.0.0:8080]
Feb 03, 2015 1:43:46 PM org.glassfish.grizzly.servlet.ServletContextImpl log
INFO: Initializing Spring root WebApplicationContext
```

Finally I could make it work by using `sudo`.

``` bash
rainer@ubuntu:~$ sudo a127 usergrid start
```

Still no luck on Windows 8.1 though, even when trying to run the command inside an `admin prompt`.

I close this for the time being as I don't see a clear pattern here. 

Maybe you could provide a vagrant linux box with all the prerequisites installed in the future :).

**Comment by satishbhakta** [comment]
I'm getting same issue on my windows 7 m/c; pls update how your issue was fixed
************Error log************
starting...
timeout
failed to start. Log tail:
INFO: Registering Spring bean, rootResource, of type org.apache.usergrid.rest.Ro
otResource as a root resource class
May 02, 2017 11:04:45 PM com.sun.jersey.spi.spring.container.SpringComponentProv
iderFactory registerSpringBeans
INFO: Registering Spring bean, systemResource, of type org.apache.usergrid.rest.
SystemResource as a root resource class
May 02, 2017 11:04:45 PM com.sun.jersey.spi.spring.container.SpringComponentProv
iderFactory registerSpringBeans
INFO: Registering Spring bean, propertiesResource, of type org.apache.usergrid.r
est.test.PropertiesResource as a root resource class
May 02, 2017 11:04:45 PM com.sun.jersey.server.impl.application.WebApplicationIm
pl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.18 11/22/2013 01:21 AM'
May 02, 2017 11:04:46 PM org.glassfish.grizzly.http.server.HttpServer start
INFO: [HttpServer] Started.

when tried to start portal, it gives error that "Usergrid isn't running.."

when tried to restart grid, get below error msg

Error: Port 8080 in use. Stop Usergrid process (or other process using port) and
try again.
at C:\SDB\Software\nodejs\node_modules\apigee-127\lib\commands\service\userg
rid.js:133:17
at C:\SDB\Software\nodejs\node_modules\apigee-127\node_modules\lodash\index.
js:7363:25
at Socket. (C:\SDB\Software\nodejs\node_modules\apigee-127\lib\ut
il\net.js:51:5)
at Object.onceWrapper (events.js:293:19)
at emitNone (events.js:86:13)
at Socket.emit (events.js:188:7)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1084:10)

when tried to kill process using 8080 and restart usergrid, get same error as first error above..
